[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['cd server && npm run build']

[start]
cmd = 'cd server && npm run start:production'